### POST request to create a new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "test",
  "email": "john2@example.com",
  "address": "1234 main street",
  "dateOfBirth": "1995-09-23"
}

###