### POST request to create a new patient
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "name": "Hamada Reda",
  "email": "hamadar@example.com",
  "phone": "01203901533",
  "address": "1234 main street",
  "dateOfBirth": "1995-09-23"
}

###