### Update an existing patient
PUT http://localhost:4004/api/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "John Doe222",
  "email": "joh2@example.com",
  "phone": "01012345661",
  "address": "4444 main street",
  "dateOfBirth": "2000-09-05"
}

###